server:
  port: 8080

spring:
  application:
    name: event-system

resilience4j:
  circuitbreaker:
    configs:
      eventService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      eventService:
        baseConfig: eventService